name: FastAPI Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to Kubernetes with Helm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
          kubectl config get-contexts

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Helm upgrade/install devops-app
        run: |
          helm upgrade --install devops-app ./fastapi-app/helm-chart \
            --namespace devops-app \
            --create-namespace \
            -f fastapi-app/helm-chart/values.yaml
